spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/flyway_test
    username: root
    password: root

  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
